# Generated by Django 5.0.3 on 2024-03-15 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='textfile',
            name='file_name',
            field=models.CharField(default='deneme', max_length=100),
            preserve_default=False,
        ),
    ]
