# Generated by Django 5.0.3 on 2024-03-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0002_package_total_count_package_uuid_textfile_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='file_name',
            new_name='name',
        ),
    ]
