# Generated by Django 5.0.3 on 2024-03-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_logs', '0003_rename_file_name_textfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
