# Generated by Django 5.0.3 on 2024-03-14 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfirmList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_no', models.CharField(max_length=56)),
                ('is_used', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('user_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, max_length=512)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('subscription_type', models.CharField(choices=[('FREE', 'Free Subscription'), ('BASIC', 'Basic Subscription'), ('PREMIUM', 'Premium Subscription')], default='FREE', max_length=16)),
                ('remaining_credits', models.IntegerField(default=5)),
                ('has_accepted_policy', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=600)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
