# Generated by Django 5.0.3 on 2024-03-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='remaining_credits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_type',
        ),
    ]
