# Generated by Django 5.0.3 on 2024-03-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='text_files/')),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.PositiveIntegerField()),
                ('time_generated', models.DateTimeField()),
                ('source_user_name', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('device_event_class_id', models.CharField(max_length=100)),
                ('text_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='panel.textfile')),
            ],
        ),
    ]
